# Generated by Django 3.0.2 on 2020-02-04 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iv_item_specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='iv_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.CharField(blank=True, max_length=64)),
                ('product_name', models.CharField(blank=True, max_length=64)),
                ('quantitity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('specification_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.iv_item_specification')),
            ],
        ),
    ]
