# Generated by Django 3.0.2 on 2020-02-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Imya')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=120, verbose_name='Phone')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='Opisanie')),
            ],
            options={
                'verbose_name': 'Forma obratnoy svyazi',
                'verbose_name_plural': 'Formi obratnoy svyazi',
            },
        ),
    ]
