# Generated by Django 3.0.2 on 2020-02-09 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Order:'),
            preserve_default=False,
        ),
    ]
